package sop_corba;


/**
* sop_corba/_ServidorCobrosStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public class _ServidorCobrosStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.ServidorCobros
{

  public sop_corba.ClsCalculosDTO calcularCosto (String placa)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("calcularCosto", true);
                $out.write_string (placa);
                $in = _invoke ($out);
                sop_corba.ClsCalculosDTO $result = sop_corba.ClsCalculosDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return calcularCosto (placa        );
            } finally {
                _releaseReply ($in);
            }
  } // calcularCosto

  public boolean registrarPago (sop_corba.ClsPagoDTO objPago)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPago", true);
                sop_corba.ClsPagoDTOHelper.write ($out, objPago);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarPago (objPago        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPago

  public sop_corba.ClsVehiculoDTO[] listarVehiculosDentro ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarVehiculosDentro", true);
                $in = _invoke ($out);
                sop_corba.ClsVehiculoDTO $result[] = sop_corba.ServidorCobrosPackage.listVehiculosDentroHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarVehiculosDentro (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarVehiculosDentro

  public sop_corba.ClsInformeDTO[] consultarInformeCostos ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarInformeCostos", true);
                $in = _invoke ($out);
                sop_corba.ClsInformeDTO $result[] = sop_corba.ServidorCobrosPackage.listInformeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarInformeCostos (        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarInformeCostos

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ServidorCobros:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServidorCobrosStub
