package sop_corba;


/**
* sop_corba/audioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 01:34:52 AM COT
*/

public final class audioHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public audioHolder ()
  {
  }

  public audioHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.audioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.audioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.audioHelper.type ();
  }

}
