package sop_corba;


/**
* sop_corba/CallBack.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 07:20:39 AM COT
*/

public interface CallBack extends CallBackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallBack
