package sop_corba;


/**
* sop_corba/CallBackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 07:20:39 AM COT
*/

public interface CallBackOperations 
{
  void recibirNoti (sop_corba.ClsDatosNotifyDTO objDatNotify);
} // interface CallBackOperations
