package sop_corba;

/**
* sop_corba/CallBackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 07:20:39 AM COT
*/

public final class CallBackHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.CallBack value = null;

  public CallBackHolder ()
  {
  }

  public CallBackHolder (sop_corba.CallBack initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.CallBackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.CallBackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.CallBackHelper.type ();
  }

}
