package sop_corba;


/**
* sop_corba/ClsCalculosDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public final class ClsCalculosDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getHoras() {
        return horas;
    }

    public void setHoras(int horas) {
        this.horas = horas;
    }

    public float getCosto() {
        return costo;
    }

    public void setCosto(float costo) {
        this.costo = costo;
    }

    public float getCostoHora() {
        return costoHora;
    }

    public void setCostoHora(float costoHora) {
        this.costoHora = costoHora;
    }
  public int horas = (int)0;
  public float costo = (float)0;
  public float costoHora = (float)0;

  public ClsCalculosDTO ()
  {
  } // ctor

  public ClsCalculosDTO (int _id, int _horas, float _costo, float _costoHora)
  {
    id = _id;
    horas = _horas;
    costo = _costo;
    costoHora = _costoHora;
  } // ctor

} // class ClsCalculosDTO
