package sop_corba;

/**
* sop_corba/ClsDatosNotifyDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 07:20:39 AM COT
*/

public final class ClsDatosNotifyDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ClsDatosNotifyDTO value = null;

  public ClsDatosNotifyDTOHolder ()
  {
  }

  public ClsDatosNotifyDTOHolder (sop_corba.ClsDatosNotifyDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ClsDatosNotifyDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ClsDatosNotifyDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ClsDatosNotifyDTOHelper.type ();
  }

}
