package sop_corba;


/**
* sop_corba/ClsDatosNotifyDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 07:20:39 AM COT
*/

public final class ClsDatosNotifyDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int opcion = (int)0;

    public int getOpcion() {
        return opcion;
    }

    public void setOpcion(int opcion) {
        this.opcion = opcion;
    }

    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }
  public String placa = null;
  public String fecha = null;
  public String hora = null;

  public ClsDatosNotifyDTO ()
  {
  } // ctor

  public ClsDatosNotifyDTO (int _opcion, String _placa, String _fecha, String _hora)
  {
    opcion = _opcion;
    placa = _placa;
    fecha = _fecha;
    hora = _hora;
  } // ctor

} // class ClsDatosNotifyDTO
