package sop_corba;


/**
* sop_corba/ClsInformeDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public final class ClsInformeDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String placa = null;
  public String fechaEntrada = null;

    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public String getFechaEntrada() {
        return fechaEntrada;
    }

    public void setFechaEntrada(String fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }

    public String getHoraEntrada() {
        return horaEntrada;
    }

    public void setHoraEntrada(String horaEntrada) {
        this.horaEntrada = horaEntrada;
    }

    public String getFechaSalida() {
        return fechaSalida;
    }

    public void setFechaSalida(String fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    public String getHoraSalida() {
        return horaSalida;
    }

    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }

    public int getHorasPaqrueo() {
        return horasPaqrueo;
    }

    public void setHorasPaqrueo(int horasPaqrueo) {
        this.horasPaqrueo = horasPaqrueo;
    }

    public float getCostoParqueo() {
        return costoParqueo;
    }

    public void setCostoParqueo(float costoParqueo) {
        this.costoParqueo = costoParqueo;
    }

    public String getNoTicket() {
        return noTicket;
    }

    public void setNoTicket(String noTicket) {
        this.noTicket = noTicket;
    }
  public String horaEntrada = null;
  public String fechaSalida = null;
  public String horaSalida = null;
  public int horasPaqrueo = (int)0;
  public float costoParqueo = (float)0;
  public String noTicket = null;

  public ClsInformeDTO ()
  {
  } // ctor

  public ClsInformeDTO (String _placa, String _fechaEntrada, String _horaEntrada, String _fechaSalida, String _horaSalida, int _horasPaqrueo, float _costoParqueo, String _noTicket)
  {
    placa = _placa;
    fechaEntrada = _fechaEntrada;
    horaEntrada = _horaEntrada;
    fechaSalida = _fechaSalida;
    horaSalida = _horaSalida;
    horasPaqrueo = _horasPaqrueo;
    costoParqueo = _costoParqueo;
    noTicket = _noTicket;
  } // ctor

} // class ClsInformeDTO
