package sop_corba;


/**
* sop_corba/ClsInformeDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

abstract public class ClsInformeDTOHelper
{
  private static String  _id = "IDL:sop_corba/ClsInformeDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.ClsInformeDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.ClsInformeDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [8];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "placa",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "fechaEntrada",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "horaEntrada",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "fechaSalida",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "horaSalida",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "horasPaqrueo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[6] = new org.omg.CORBA.StructMember (
            "costoParqueo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "noTicket",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.ClsInformeDTOHelper.id (), "ClsInformeDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.ClsInformeDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.ClsInformeDTO value = new sop_corba.ClsInformeDTO ();
    value.placa = istream.read_string ();
    value.fechaEntrada = istream.read_string ();
    value.horaEntrada = istream.read_string ();
    value.fechaSalida = istream.read_string ();
    value.horaSalida = istream.read_string ();
    value.horasPaqrueo = istream.read_long ();
    value.costoParqueo = istream.read_float ();
    value.noTicket = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.ClsInformeDTO value)
  {
    ostream.write_string (value.placa);
    ostream.write_string (value.fechaEntrada);
    ostream.write_string (value.horaEntrada);
    ostream.write_string (value.fechaSalida);
    ostream.write_string (value.horaSalida);
    ostream.write_long (value.horasPaqrueo);
    ostream.write_float (value.costoParqueo);
    ostream.write_string (value.noTicket);
  }

}
