package sop_corba;


/**
* sop_corba/ClsRespuestaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 01:34:52 AM COT
*/

public final class ClsRespuestaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int opcion = (int)0;

    public int getOpcion() {
        return opcion;
    }

    public void setOpcion(int opcion) {
        this.opcion = opcion;
    }

    public byte[] getMensajeAudio() {
        return mensajeAudio;
    }

    public void setMensajeAudio(byte[] mensajeAudio) {
        this.mensajeAudio = mensajeAudio;
    }
  public byte mensajeAudio[] = null;

  public ClsRespuestaDTO ()
  {
  } // ctor

  public ClsRespuestaDTO (int _opcion, byte[] _mensajeAudio)
  {
    opcion = _opcion;
    mensajeAudio = _mensajeAudio;
  } // ctor

} // class ClsRespuestaDTO
