package sop_corba;


/**
* sop_corba/ClsVehiculoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public final class ClsVehiculoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String placa = null;
  public String fecha = null;

    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }
  public String hora = null;

  public ClsVehiculoDTO ()
  {
  } // ctor

  public ClsVehiculoDTO (String _placa, String _fecha, String _hora)
  {
    placa = _placa;
    fecha = _fecha;
    hora = _hora;
  } // ctor

} // class ClsVehiculoDTO
