package sop_corba;


/**
* sop_corba/ServidorCobrosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public abstract class ServidorCobrosPOA extends org.omg.PortableServer.Servant
 implements sop_corba.ServidorCobrosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calcularCosto", new java.lang.Integer (0));
    _methods.put ("registrarPago", new java.lang.Integer (1));
    _methods.put ("listarVehiculosDentro", new java.lang.Integer (2));
    _methods.put ("consultarInformeCostos", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/ServidorCobros/calcularCosto
       {
         String placa = in.read_string ();
         sop_corba.ClsCalculosDTO $result = null;
         $result = this.calcularCosto (placa);
         out = $rh.createReply();
         sop_corba.ClsCalculosDTOHelper.write (out, $result);
         break;
       }

       case 1:  // sop_corba/ServidorCobros/registrarPago
       {
         sop_corba.ClsPagoDTO objPago = sop_corba.ClsPagoDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarPago (objPago);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/ServidorCobros/listarVehiculosDentro
       {
         sop_corba.ClsVehiculoDTO $result[] = null;
         $result = this.listarVehiculosDentro ();
         out = $rh.createReply();
         sop_corba.ServidorCobrosPackage.listVehiculosDentroHelper.write (out, $result);
         break;
       }

       case 3:  // sop_corba/ServidorCobros/consultarInformeCostos
       {
         sop_corba.ClsInformeDTO $result[] = null;
         $result = this.consultarInformeCostos ();
         out = $rh.createReply();
         sop_corba.ServidorCobrosPackage.listInformeHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ServidorCobros:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServidorCobros _this() 
  {
    return ServidorCobrosHelper.narrow(
    super._this_object());
  }

  public ServidorCobros _this(org.omg.CORBA.ORB orb) 
  {
    return ServidorCobrosHelper.narrow(
    super._this_object(orb));
  }


} // class ServidorCobrosPOA
