package sop_corba;

/**
* sop_corba/ServidorCobrosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public final class ServidorCobrosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ServidorCobros value = null;

  public ServidorCobrosHolder ()
  {
  }

  public ServidorCobrosHolder (sop_corba.ServidorCobros initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ServidorCobrosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ServidorCobrosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ServidorCobrosHelper.type ();
  }

}
