package sop_corba;


/**
* sop_corba/ServidorCobrosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public interface ServidorCobrosOperations 
{
  sop_corba.ClsCalculosDTO calcularCosto (String placa);
  boolean registrarPago (sop_corba.ClsPagoDTO objPago);
  sop_corba.ClsVehiculoDTO[] listarVehiculosDentro ();
  sop_corba.ClsInformeDTO[] consultarInformeCostos ();
} // interface ServidorCobrosOperations
