package sop_corba;


/**
* sop_corba/ServidorCobrosPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public class ServidorCobrosPOATie extends ServidorCobrosPOA
{

  // Constructors

  public ServidorCobrosPOATie ( sop_corba.ServidorCobrosOperations delegate ) {
      this._impl = delegate;
  }
  public ServidorCobrosPOATie ( sop_corba.ServidorCobrosOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public sop_corba.ServidorCobrosOperations _delegate() {
      return this._impl;
  }
  public void _delegate (sop_corba.ServidorCobrosOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public sop_corba.ClsCalculosDTO calcularCosto (String placa)
  {
    return _impl.calcularCosto(placa);
  } // calcularCosto

  public boolean registrarPago (sop_corba.ClsPagoDTO objPago)
  {
    return _impl.registrarPago(objPago);
  } // registrarPago

  public sop_corba.ClsVehiculoDTO[] listarVehiculosDentro ()
  {
    return _impl.listarVehiculosDentro();
  } // listarVehiculosDentro

  public sop_corba.ClsInformeDTO[] consultarInformeCostos ()
  {
    return _impl.consultarInformeCostos();
  } // consultarInformeCostos

  private sop_corba.ServidorCobrosOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ServidorCobrosPOATie
