package sop_corba;


/**
* sop_corba/SolucionPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 01:34:52 AM COT
*/

public class SolucionPOATie extends SolucionPOA
{

  // Constructors

  public SolucionPOATie ( sop_corba.SolucionOperations delegate ) {
      this._impl = delegate;
  }
  public SolucionPOATie ( sop_corba.SolucionOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public sop_corba.SolucionOperations _delegate() {
      return this._impl;
  }
  public void _delegate (sop_corba.SolucionOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public sop_corba.ClsRespuestaDTO enviarPlacaAutomovilEntrada (String placa)
  {
    return _impl.enviarPlacaAutomovilEntrada(placa);
  } // enviarPlacaAutomovilEntrada

  public sop_corba.ClsRespuestaDTO enviarPlacaAutomovilSalida (String placa)
  {
    return _impl.enviarPlacaAutomovilSalida(placa);
  } // enviarPlacaAutomovilSalida

  private sop_corba.SolucionOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class SolucionPOATie
