package sop_corba;


/**
* sop_corba/SolucionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 01:34:52 AM COT
*/

public interface SolucionOperations 
{
  sop_corba.ClsRespuestaDTO enviarPlacaAutomovilEntrada (String placa);
  sop_corba.ClsRespuestaDTO enviarPlacaAutomovilSalida (String placa);
} // interface SolucionOperations
