package sop_corba;


/**
* sop_corba/Solucion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 01:34:52 AM COT
*/

public interface Solucion extends SolucionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Solucion
