package sop_corba;

/**
* sop_corba/SolucionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 01:34:52 AM COT
*/

public final class SolucionHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.Solucion value = null;

  public SolucionHolder ()
  {
  }

  public SolucionHolder (sop_corba.Solucion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.SolucionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.SolucionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.SolucionHelper.type ();
  }

}
