package sop_corba;


/**
* sop_corba/SolucionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 01:34:52 AM COT
*/

public abstract class SolucionPOA extends org.omg.PortableServer.Servant
 implements sop_corba.SolucionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("enviarPlacaAutomovilEntrada", new java.lang.Integer (0));
    _methods.put ("enviarPlacaAutomovilSalida", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/Solucion/enviarPlacaAutomovilEntrada
       {
         String placa = in.read_string ();
         sop_corba.ClsRespuestaDTO $result = null;
         $result = this.enviarPlacaAutomovilEntrada (placa);
         out = $rh.createReply();
         sop_corba.ClsRespuestaDTOHelper.write (out, $result);
         break;
       }

       case 1:  // sop_corba/Solucion/enviarPlacaAutomovilSalida
       {
         String placa = in.read_string ();
         sop_corba.ClsRespuestaDTO $result = null;
         $result = this.enviarPlacaAutomovilSalida (placa);
         out = $rh.createReply();
         sop_corba.ClsRespuestaDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/Solucion:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Solucion _this() 
  {
    return SolucionHelper.narrow(
    super._this_object());
  }

  public Solucion _this(org.omg.CORBA.ORB orb) 
  {
    return SolucionHelper.narrow(
    super._this_object(orb));
  }


} // class SolucionPOA
