package sop_corba.ServidorCobrosPackage;


/**
* sop_corba/ServidorCobrosPackage/listVehiculosDentroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 26 de marzo de 2019 04:20:22 AM COT
*/

public final class listVehiculosDentroHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ClsVehiculoDTO value[] = null;

  public listVehiculosDentroHolder ()
  {
  }

  public listVehiculosDentroHolder (sop_corba.ClsVehiculoDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ServidorCobrosPackage.listVehiculosDentroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ServidorCobrosPackage.listVehiculosDentroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ServidorCobrosPackage.listVehiculosDentroHelper.type ();
  }

}
