/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador.Vista;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sop_corba.ClsCalculosDTO;
import sop_corba.ClsInformeDTO;
import sop_corba.ClsPagoDTO;
import sop_corba.ClsVehiculoDTO;
import sop_corba.ServidorCobros;
import sop_corba.ClsDatosNotifyDTO;
import sop_corba.*;
import org.omg.CosNaming.*;
import org.omg.CORBA.ORB;
import org.omg.PortableServer.*;
import org.omg.PortableServer.POA;


/**
 *
 * @author USUARIO
 */
public class GUIAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form GUIAdministrador
     */
    ServidorCobros objSol;
    ClsCalculosDTO objCal;
    ClsPagoDTO objPag;
    public GUIAdministrador() {
        initComponents();
    }
    
     public GUIAdministrador(ServidorCobros objSol) {
         
         this.objSol=objSol;
         initComponents();
         jLblCostoPar.setVisible(false);
         jLblNoTi.setVisible(false);
         jLblTicke.setVisible(false);
         jBtnRegPa.setVisible(false);
         jTxtFiCosto.setVisible(false);
         jTxtFiNoTicket.setVisible(false);
         jCbxTick.setVisible(false);
         jTxtHora.setVisible(false);
         jLblHoras.setVisible(false);
         jLblCostoHora.setVisible(false);
         jTxtFiCostoHora.setVisible(false);

         


         try{       

            String[] vector= new String[4];
            vector[0]="–ORBInitialHost";
            vector[1]="localhost";
            vector[2]="-ORBInitialPort";
            vector[3]="2020";
    // crea e iniciia el ORB
    ORB orb = ORB.init(vector, null);

    // obtiene la referencia del rootpoa & activate el POAManager
    POA rootpoa = 
    POAHelper.narrow(orb.resolve_initial_references("RootPOA"));
    rootpoa.the_POAManager().activate();

    // crea el servant y lo registra con el ORB
    CallBackImpl convref = new CallBackImpl(this);

    // obtiene la referencia del objeto desde el servant
    org.omg.CORBA.Object obj = rootpoa.servant_to_reference(convref);
    CallBack href = CallBackHelper.narrow(obj);

    // obtiene la base del contexto de nombrado
    org.omg.CORBA.Object objref = orb.resolve_initial_references("NameService");
    // Usa NamingContextExt el cual es parte de la especificacion 
    // Naming Service (INS).
    NamingContextExt ncref = NamingContextExtHelper.narrow(objref);

    // Realiza el binding de la referencia de objeto en el N_S
    String name ="objCallBack";
    NameComponent path[] = ncref.to_name( name );
    ncref.rebind(path, href);

    System.out.println("El Servidor esta listo y esperando ...");

    // esperan por las invocaciones desde los clientes
   
    } 

    catch (Exception e) {
    System.err.println("ERROR: " + e);
    e.printStackTrace(System.out);
    }


    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTxtFiPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLblCostoPar = new javax.swing.JLabel();
        jTxtFiCosto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCbxTick = new javax.swing.JComboBox<>();
        jLblTicke = new javax.swing.JLabel();
        jLblNoTi = new javax.swing.JLabel();
        jTxtFiNoTicket = new javax.swing.JTextField();
        jBtnRegPa = new javax.swing.JButton();
        jLblHoras = new javax.swing.JLabel();
        jTxtHora = new javax.swing.JTextField();
        jLblCostoHora = new javax.swing.JLabel();
        jTxtFiCostoHora = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblDentro = new javax.swing.JTable();
        jBtnListar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblInforme = new javax.swing.JTable();
        jBtnGeInforme = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Placa");

        jLblCostoPar.setText("Costo Parqueo");

        jTxtFiCosto.setEnabled(false);

        jButton1.setText("Consultar Costo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCbxTick.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si" }));
        jCbxTick.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbxTickItemStateChanged(evt);
            }
        });

        jLblTicke.setText("Ticket");

        jLblNoTi.setText("No Ticket");

        jBtnRegPa.setText("Registrar Pago");
        jBtnRegPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegPaActionPerformed(evt);
            }
        });

        jLblHoras.setText("Horas Transcurridas");

        jTxtHora.setEnabled(false);

        jLblCostoHora.setText("Costo Por Hora");

        jTxtFiCostoHora.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFiPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblHoras)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblTicke)
                                        .addComponent(jLblNoTi))
                                    .addGap(27, 27, 27))
                                .addComponent(jLblCostoPar, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLblCostoHora))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFiCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(jTxtHora)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCbxTick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFiNoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnRegPa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtFiCostoHora))))
                .addGap(92, 92, 92))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFiPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCostoHora)
                    .addComponent(jTxtFiCostoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblHoras)
                    .addComponent(jTxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFiCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCostoPar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbxTick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTicke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNoTi)
                    .addComponent(jTxtFiNoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnRegPa)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registrar Cobro Vehiculo", jPanel3);

        jTblDentro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Fecha Entrada", "Hora Entrada"
            }
        ));
        jScrollPane1.setViewportView(jTblDentro);

        jBtnListar.setText("Listar ");
        jBtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnListar)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar vehiculos dentro ", jPanel4);

        jTblInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Fecha Entrada", "Hora Entrada", "Fecha Salida", "Hora Salida", "Horas Parqueo", "Costo Parqueo", "No Ticket"
            }
        ));
        jScrollPane2.setViewportView(jTblInforme);

        jBtnGeInforme.setText("Generar Informe");
        jBtnGeInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGeInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnGeInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnGeInforme)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar costos de los vehículos", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
        objCal=objSol.calcularCosto(jTxtFiPlaca.getText());
        if(objCal.getCosto()!=-1)
        {
                jTxtHora.setText(""+objCal.getHoras());
                jTxtFiCosto.setText(""+objCal.costo);
                jTxtFiCostoHora.setText(""+objCal.getCostoHora());
                jLblCostoPar.setVisible(true);
                jLblTicke.setVisible(true);
                jBtnRegPa.setVisible(true);
                jTxtFiCosto.setVisible(true);
                jCbxTick.setVisible(true);
                jTxtHora.setVisible(true);
                jLblHoras.setVisible(true);
                jLblCostoHora.setVisible(true);
                jTxtFiCostoHora.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "No existen registros de entrada para este vehiculo!!!");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCbxTickItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbxTickItemStateChanged
        // TODO add your handling code here:
          if (jCbxTick.getSelectedItem().toString().equals("Si"))
        {
                 jTxtFiNoTicket.setVisible(true);
                 jLblNoTi.setVisible(true);
                 jTxtFiCosto.setText("0.0");
        }
        
    }//GEN-LAST:event_jCbxTickItemStateChanged

    private void jBtnRegPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegPaActionPerformed
        // TODO add your handling code here:
        String noTicket;
        objPag= new ClsPagoDTO();
        objPag.setId(objCal.getId());
        objPag.setPlaca(jTxtFiPlaca.getText());
        if (jCbxTick.getSelectedItem().toString().equals("Si"))
        {
            if(jTxtFiNoTicket.getText().equals(""))                
                    JOptionPane.showMessageDialog(null, "Por favor ingrese el numero del ticket!!!");
            else{
                noTicket=jTxtFiNoTicket.getText();
                objPag.setNoTicket(noTicket);
            }
        }
        else
            objPag.setNoTicket("");
        
        
       if(objSol.registrarPago(objPag))
       {
             JOptionPane.showMessageDialog(null, "Registro de pago exitoso!!!");
         jLblCostoPar.setVisible(false);
         jLblNoTi.setVisible(false);
         jLblTicke.setVisible(false);
         jBtnRegPa.setVisible(false);
         jTxtFiCosto.setVisible(false);
         jTxtFiNoTicket.setVisible(false);
         jCbxTick.setVisible(false);
         jTxtHora.setVisible(false);
         jLblHoras.setVisible(false);
         jLblCostoHora.setVisible(false);
         jTxtFiCostoHora.setVisible(false);
         jTxtFiPlaca.setText("");
       }

           
    }//GEN-LAST:event_jBtnRegPaActionPerformed



    private void jBtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarActionPerformed
        // TODO add your handling code here:
          
         DefaultTableModel tb = (DefaultTableModel) jTblDentro.getModel(); 

        int a = jTblDentro.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        } 
 
        
        
        
        ClsVehiculoDTO[] vehiculos=objSol.listarVehiculosDentro();
        
         DefaultTableModel modelo=(DefaultTableModel) jTblDentro.getModel(); 
 
        //Sección 2
        Object [] fila=new Object[3]; 
 
        //Sección 3
         if(vehiculos.length==0)
        {
             JOptionPane.showMessageDialog(null, "No ahi vehiculos dentro del parqueadero!!!");
        }
        
        for(int i=0; i< vehiculos.length; i++)
        {
            fila[0]=vehiculos[i].getPlaca(); 
            fila[1]=vehiculos[i].getFecha(); 
            fila[2]=vehiculos[i].getHora(); 

             //Sección 4
             modelo.addRow(fila); 
        }
  
        //Sección 5
        jTblDentro.setModel(modelo); 
    }//GEN-LAST:event_jBtnListarActionPerformed

    private void jBtnGeInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGeInformeActionPerformed
        // TODO add your handling code here:
        
        ClsInformeDTO[] vectorInforme= objSol.consultarInformeCostos();
        
        DefaultTableModel tb = (DefaultTableModel) jTblInforme.getModel(); 

        int a = jTblInforme.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        } 
 
        
        
        
       
        
         DefaultTableModel modelo=(DefaultTableModel) jTblInforme.getModel(); 
 
        //Sección 2
        Object [] fila=new Object[8]; 
 
        //Sección 3
        if(vectorInforme.length==0)
        {
             JOptionPane.showMessageDialog(null, "No existen informes por generar!!!");
        }
        for(int i=0; i< vectorInforme.length; i++)
        {
            fila[0]=vectorInforme[i].getPlaca(); 
            fila[1]=vectorInforme[i].getFechaEntrada(); 
            fila[2]=vectorInforme[i].getHoraEntrada(); 
            fila[3]=vectorInforme[i].getFechaSalida(); 
            fila[4]=vectorInforme[i].getHoraSalida(); 
            fila[5]=vectorInforme[i].getHorasPaqrueo(); 
            fila[6]=vectorInforme[i].getCostoParqueo(); 
            fila[7]=vectorInforme[i].getNoTicket(); 
            

             //Sección 4
             modelo.addRow(fila); 
        }
  
        //Sección 5
        jTblInforme.setModel(modelo); 
    }//GEN-LAST:event_jBtnGeInformeActionPerformed

    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAdministrador().setVisible(true);
            }
        });
    }

    public void mostrarNotify(ClsDatosNotifyDTO objNotify)
    {
        if(objNotify.getOpcion()==1)
        {
            JOptionPane.showMessageDialog(null, "Registro nuevo entrada PLACA: "+objNotify.getPlaca()+" FECHA ENTRADA:"+objNotify.getFecha()+" HORA ENTRADA: "+objNotify.getHora());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Registro nuevo salida PLACA: "+objNotify.getPlaca()+" FECHA SALIDA:"+objNotify.getFecha()+" HORA SALIDA: "+objNotify.getHora());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGeInforme;
    private javax.swing.JButton jBtnListar;
    private javax.swing.JButton jBtnRegPa;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCbxTick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblCostoHora;
    private javax.swing.JLabel jLblCostoPar;
    private javax.swing.JLabel jLblHoras;
    private javax.swing.JLabel jLblNoTi;
    private javax.swing.JLabel jLblTicke;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTblDentro;
    private javax.swing.JTable jTblInforme;
    private javax.swing.JTextField jTxtFiCosto;
    private javax.swing.JTextField jTxtFiCostoHora;
    private javax.swing.JTextField jTxtFiNoTicket;
    private javax.swing.JTextField jTxtFiPlaca;
    private javax.swing.JTextField jTxtHora;
    // End of variables declaration//GEN-END:variables
}
